#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

name: Test Code Base
on: [push, pull_request]
jobs:
    build:
        name: Test Code Base
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  check-latest: true
            - run: npm run install-all
            - run: npm run lint
            - run: npm test
